<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-19T17:21:09 GMT-04:00" name="Suite" finished-at="2024-09-19T17:21:51 GMT-04:00" duration-ms="41811">
    <groups>
      <group name="ErrorHandling">
        <method signature="Errorvalidation.checkOutWithOutCountry()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" name="checkOutWithOutCountry" class="yashwanthgunapatiqa.tests.Errorvalidation"/>
        <method signature="Errorvalidation.loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" name="loginErrorValidation" class="yashwanthgunapatiqa.tests.Errorvalidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-09-19T17:21:09 GMT-04:00" name="Errors Validation in Application" finished-at="2024-09-19T17:21:50 GMT-04:00" duration-ms="40619">
      <class name="yashwanthgunapatiqa.tests.Errorvalidation">
        <test-method is-config="true" signature="launchWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:09 GMT-04:00" name="launchWebSite" finished-at="2024-09-19T17:21:18 GMT-04:00" duration-ms="8983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebSite -->
        <test-method signature="checkOutWithOutCountry()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:18 GMT-04:00" name="checkOutWithOutCountry" finished-at="2024-09-19T17:21:27 GMT-04:00" duration-ms="8542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOutWithOutCountry -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:27 GMT-04:00" name="quitBrowser" finished-at="2024-09-19T17:21:29 GMT-04:00" duration-ms="1876" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="launchWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:29 GMT-04:00" name="launchWebSite" finished-at="2024-09-19T17:21:37 GMT-04:00" duration-ms="7926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebSite -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:37 GMT-04:00" name="loginErrorValidation" finished-at="2024-09-19T17:21:38 GMT-04:00" duration-ms="1222" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password entered] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password entered] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at yashwanthgunapatiqa.tests.Errorvalidation.loginErrorValidation(Errorvalidation.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:38 GMT-04:00" name="quitBrowser" finished-at="2024-09-19T17:21:39 GMT-04:00" duration-ms="749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="launchWebSite()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:39 GMT-04:00" name="launchWebSite" finished-at="2024-09-19T17:21:46 GMT-04:00" duration-ms="7508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchWebSite -->
        <test-method signature="loginErrorValidation()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:46 GMT-04:00" name="loginErrorValidation" finished-at="2024-09-19T17:21:47 GMT-04:00" duration-ms="1091" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password entered] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password entered] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at yashwanthgunapatiqa.tests.Errorvalidation.loginErrorValidation(Errorvalidation.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:yashwanthgunapatiqa.tests.Errorvalidation@2b30a42c]" started-at="2024-09-19T17:21:48 GMT-04:00" name="quitBrowser" finished-at="2024-09-19T17:21:50 GMT-04:00" duration-ms="1513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- yashwanthgunapatiqa.tests.Errorvalidation -->
    </test> <!-- Errors Validation in Application -->
    <test started-at="2024-09-19T17:21:51 GMT-04:00" name="Ordering the Products" finished-at="2024-09-19T17:21:51 GMT-04:00" duration-ms="0">
    </test> <!-- Ordering the Products -->
  </suite> <!-- Suite -->
</testng-results>
